version: "3"
services:
    seconds-contract:
        build: ./contract-system
        restart: always
        container_name: contract-system
        ports:
            - "8000:8000"
            - "9000:9000"
        networks:
            - custom_net


networks:
    custom_net:
        external:
            name: app_net
